spring:
  application:
    name: BrokersTest

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: ${SPRING_RABBITMQ_PORT}
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}

server:
  port: ${SERVER_PORT}

broker:
  type: ${BROKER_TYPE}

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
  group-id: ${KAFKA_GROUP_ID}
  auto-offset-reset: ${KAFKA_AUTO_OFFSET_RESET}
  topic:
    movies-events: ${KAFKA_TOPIC_MOVIE_EVENTS}
    watch-events: ${KAFKA_TOPIC_WATCH_EVENTS}

rabbitmq:
  queue:
    movie: ${RABBITMQ_QUEUE_MOVIE}
    watch: ${RABBITMQ_QUEUE_WATCH}
